image: rocker/geospatial:latest

stages:
  - build

render_rayshader:
  stage: build
  before_script:
    - R --vanilla -e "install.packages(c('rayshader', 'biscale'), repos = 'http://cran.rstudio.com')"
  script:
    - Rscript --vanilla src/render_rayshader.R 
  artifacts:
    paths:
      - public
