name: Render rayshader

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: rocker/geospatial:latest

    steps:
    - name: Install git-lfs
      run: |
        apt-get update
        apt-get install -y git-lfs
        git lfs install

    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Install R packages
      id: setup
      run: R --vanilla -e "install.packages(c('rayshader', 'biscale'), repos = 'http://cran.rstudio.com')"

    - name: Render rayshader
      id: render
      run: Rscript --vanilla src/render_rayshader.R

    - name: Upload artifacts
      id: upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
